name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run typecheck

      - name: Build vNext
        run: npm run vnext:build

      - name: Run deterministic compose test
        run: |
          # Create artifacts directory
          mkdir -p artifacts
          
          # Run 1-cycle deterministic compose with fixed seed
          npm run compose -- --seed=12345 --mode=short
          
          # Verify artifacts were created
          if [ ! -f "artifacts/audio" ] && [ ! -f "artifacts/text" ] && [ ! -f "artifacts/viz" ]; then
            echo "❌ No artifacts generated"
            exit 1
          fi
          
          echo "✅ Artifacts generated successfully"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts-${{ github.run_id }}
          path: artifacts/
          retention-days: 7

      - name: CI Summary
        run: |
          echo "## ✅ CI Pipeline Complete" >> $GITHUB_STEP_SUMMARY
          echo "- **Build**: ✅ Successful" >> $GITHUB_STEP_SUMMARY
          echo "- **Type Check**: ✅ Passed" >> $GITHUB_STEP_SUMMARY
          echo "- **Compose Test**: ✅ 1-cycle deterministic test passed" >> $GITHUB_STEP_SUMMARY
          echo "- **Artifacts**: ✅ Generated and uploaded" >> $GITHUB_STEP_SUMMARY
